version: "3.9"

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fakestore
      POSTGRES_USER: fakestore
      POSTGRES_PASSWORD: fakestore
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # loki:
  #   image: grafana/loki:2.9.0
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:2.9.0
  #   volumes:
  #     - ./docker/promtail.yaml:/etc/promtail/config.yml
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #   command: -config.file=/etc/promtail/config.yml

  # grafana:
  #   image: grafana/grafana:10.2.0
  #   ports:
  #     - "3001:3000"


volumes:
  postgres:
